services:
  # FastAPI Application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alpha_granite_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./static/uploads:/app/static/uploads
      - ./static/defaults:/app/static/defaults
      - ./logs:/app/logs
      - /root/alphagranite/alpha-granit/static:/app/static
    entrypoint: []
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000
    environment:
      - FILE_UPLOAD_ROOT=/app/static   # root for FileService
      - UPLOAD_DIR=/app/static/jobs    # if your code reads this
      - BASE_URL=https://api.ag.easybusiness.ng
    user: "www-data"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"      # Use port 8080 instead of 80
      - "8443:443"     # Use port 8443 instead of 443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - web
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
