services:
  # FastAPI Application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alpha_granite_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./static/uploads:/app/static/uploads
      - ./static/defaults:/app/static/defaults
      - ./logs:/app/logs
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
