"""create jobs table

Revision ID: 074512f0ca0f
Revises: 834943c9a785
Create Date: 2025-11-13 04:30:01.333453

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '074512f0ca0f'
down_revision: Union[str, Sequence[str], None] = '834943c9a785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cut_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fab_id', sa.Integer(), nullable=False),
    sa.Column('is_final_progreamming_completed', sa.Boolean(), nullable=False),
    sa.Column('shop_schedule_date', sa.DateTime(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('no_of_piece', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_sqft', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('installation_date', sa.DateTime(), nullable=True),
    sa.Column('Ln_ft_map', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draftings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drafter_id', sa.Integer(), nullable=False),
    sa.Column('fab_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_start_date', sa.DateTime(), nullable=False),
    sa.Column('scheduled_end_date', sa.DateTime(), nullable=False),
    sa.Column('drafter_start_date', sa.DateTime(), nullable=True),
    sa.Column('drafter_end_date', sa.DateTime(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('file_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('no_of_piece_drafted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_sqft_required_to_draft', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_sqft_drafted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('draft_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mentions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_redrafting', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('final_programmings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drafter_id', sa.Integer(), nullable=False),
    sa.Column('fab_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_start_date', sa.DateTime(), nullable=False),
    sa.Column('scheduled_end_date', sa.DateTime(), nullable=False),
    sa.Column('drafter_start_date', sa.DateTime(), nullable=True),
    sa.Column('drafter_end_date', sa.DateTime(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('file_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('no_of_piece_drafted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_sqft_required_to_draft', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_sqft_drafted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_technician_workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fab_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pause_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_sqft_done', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_workflow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_planning_sections', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=False),
    sa.Column('total_sqft_done', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason_for_pause', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planning_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pre_draft_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fab_id', sa.Integer(), nullable=False),
    sa.Column('draft_notes', sa.Integer(), nullable=False),
    sa.Column('is_redrafting_needed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_cts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fab_id', sa.Integer(), nullable=False),
    sa.Column('is_revision_needed', sa.Boolean(), nullable=False),
    sa.Column('is_revision_completed', sa.Boolean(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('no_of_revisions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_revision_count', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('slab_smith_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('drafter_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('total_sqft_completed', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_planning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_planning_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_station_id', sa.Integer(), nullable=False),
    sa.Column('operator_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('machine', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scheduled_sqft', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('completed_sqft', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slab_smiths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fab_id', sa.Integer(), nullable=False),
    sa.Column('slab_smith_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('drafter_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('total_sqft_completed', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('file_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templatings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fab_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('schedule_start_date', sa.DateTime(), nullable=True),
    sa.Column('schedule_due_date', sa.DateTime(), nullable=True),
    sa.Column('total_sqft', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_templating_schedule', sa.Boolean(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('curremt_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_stone_types_name'), table_name='stone_types')
    op.drop_table('stone_types')
    op.drop_index(op.f('ix_stone_colors_name'), table_name='stone_colors')
    op.drop_table('stone_colors')
    op.drop_index(op.f('ix_edges_name'), table_name='edges')
    op.drop_table('edges')
    op.drop_index(op.f('ix_stone_thickness_thickness'), table_name='stone_thickness')
    op.drop_table('stone_thickness')
    op.drop_index(op.f('ix_accounts_account_number'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('account_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contact_person', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('accounts_created_by_fkey')),
    sa.ForeignKeyConstraint(['status_id'], ['status.value_id'], name=op.f('accounts_status_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('accounts_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('accounts_pkey')),
    sa.UniqueConstraint('account_number', name=op.f('accounts_account_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('name', name=op.f('accounts_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=False)
    op.create_index(op.f('ix_accounts_account_number'), 'accounts', ['account_number'], unique=False)
    op.create_table('stone_thickness',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('thickness', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('thickness_mm', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('stone_thickness_created_by_fkey')),
    sa.ForeignKeyConstraint(['status_id'], ['status.value_id'], name=op.f('stone_thickness_status_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('stone_thickness_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stone_thickness_pkey')),
    sa.UniqueConstraint('thickness', name=op.f('stone_thickness_thickness_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_stone_thickness_thickness'), 'stone_thickness', ['thickness'], unique=False)
    op.create_table('edges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('edge_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('edges_created_by_fkey')),
    sa.ForeignKeyConstraint(['status_id'], ['status.value_id'], name=op.f('edges_status_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('edges_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('edges_pkey')),
    sa.UniqueConstraint('name', name=op.f('edges_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_edges_name'), 'edges', ['name'], unique=False)
    op.create_table('stone_colors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('color_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('stone_colors_created_by_fkey')),
    sa.ForeignKeyConstraint(['status_id'], ['status.value_id'], name=op.f('stone_colors_status_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('stone_colors_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stone_colors_pkey')),
    sa.UniqueConstraint('name', name=op.f('stone_colors_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_stone_colors_name'), 'stone_colors', ['name'], unique=False)
    op.create_table('stone_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('stone_types_created_by_fkey')),
    sa.ForeignKeyConstraint(['status_id'], ['status.value_id'], name=op.f('stone_types_status_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('stone_types_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stone_types_pkey')),
    sa.UniqueConstraint('name', name=op.f('stone_types_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_stone_types_name'), 'stone_types', ['name'], unique=False)
    op.drop_table('work_stations')
    op.drop_table('templatings')
    op.drop_table('slab_smiths')
    op.drop_table('shop_planning_sections')
    op.drop_table('shop_planning')
    op.drop_table('sales_cts')
    op.drop_table('pre_draft_reviews')
    op.drop_table('planning_sections')
    op.drop_table('operation_workflow')
    op.drop_table('job_technician_workflows')
    op.drop_table('final_programmings')
    op.drop_table('draftings')
    op.drop_table('cut_list')
    # ### end Alembic commands ###
