"""create jobs table

Revision ID: 074512f0ca0f
Revises: 834943c9a785
Create Date: 2025-11-13 04:30:01.333453

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = '074512f0ca0f'
down_revision: Union[str, Sequence[str], None] = '834943c9a785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def table_exists(table_name):
    """Check if a table exists in the database."""
    conn = op.get_bind()
    from sqlalchemy import inspect
    inspector = inspect(conn)
    return table_name in inspector.get_table_names()


def create_table_if_not_exists(table_name, *args, **kwargs):
    """Create a table only if it doesn't already exist."""
    if not table_exists(table_name):
        op.create_table(table_name, *args, **kwargs)
        print(f"Created table: {table_name}")
    else:
        print(f"Skipped table (already exists): {table_name}")


def drop_table_if_exists(table_name):
    """Drop a table only if it exists."""
    if table_exists(table_name):
        op.drop_table(table_name)
        print(f"Dropped table: {table_name}")
    else:
        print(f"Skipped drop (table doesn't exist): {table_name}")


def drop_index_if_exists(index_name, table_name):
    """Drop an index only if it exists."""
    conn = op.get_bind()
    # Check if index exists first
    result = conn.execute(sa.text(f"""
        SELECT 1 FROM pg_indexes 
        WHERE indexname = '{index_name}'
    """))
    if result.scalar():
        op.drop_index(op.f(index_name), table_name=table_name)
        print(f"Dropped index: {index_name}")
    else:
        print(f"Skipped drop index (doesn't exist): {index_name}")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    create_table_if_not_exists('cut_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fab_id', sa.Integer(), nullable=False),
    sa.Column('is_final_progreamming_completed', sa.Boolean(), nullable=False),
    sa.Column('shop_schedule_date', sa.DateTime(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('no_of_piece', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_sqft', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('installation_date', sa.DateTime(), nullable=True),
    sa.Column('Ln_ft_map', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    create_table_if_not_exists('draftings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drafter_id', sa.Integer(), nullable=False),
    sa.Column('fab_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_start_date', sa.DateTime(), nullable=False),
    sa.Column('scheduled_end_date', sa.DateTime(), nullable=False),
    sa.Column('drafter_start_date', sa.DateTime(), nullable=True),
    sa.Column('drafter_end_date', sa.DateTime(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('file_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('no_of_piece_drafted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_sqft_required_to_draft', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_sqft_drafted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('draft_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mentions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_redrafting', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    create_table_if_not_exists('final_programmings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drafter_id', sa.Integer(), nullable=False),
    sa.Column('fab_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_start_date', sa.DateTime(), nullable=False),
    sa.Column('scheduled_end_date', sa.DateTime(), nullable=False),
    sa.Column('drafter_start_date', sa.DateTime(), nullable=True),
    sa.Column('drafter_end_date', sa.DateTime(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('file_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('no_of_piece_drafted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_sqft_required_to_draft', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_sqft_drafted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    create_table_if_not_exists('job_technician_workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fab_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pause_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_sqft_done', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    create_table_if_not_exists('operation_workflow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_planning_sections', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=False),
    sa.Column('total_sqft_done', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason_for_pause', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    create_table_if_not_exists('planning_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    create_table_if_not_exists('pre_draft_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fab_id', sa.Integer(), nullable=False),
    sa.Column('draft_notes', sa.Integer(), nullable=False),
    sa.Column('is_redrafting_needed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    create_table_if_not_exists('sales_cts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fab_id', sa.Integer(), nullable=False),
    sa.Column('is_revision_needed', sa.Boolean(), nullable=False),
    sa.Column('is_revision_completed', sa.Boolean(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('no_of_revisions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_revision_count', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('slab_smith_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('drafter_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('total_sqft_completed', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    create_table_if_not_exists('shop_planning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    create_table_if_not_exists('shop_planning_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_station_id', sa.Integer(), nullable=False),
    sa.Column('operator_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('machine', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scheduled_sqft', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('completed_sqft', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    create_table_if_not_exists('slab_smiths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fab_id', sa.Integer(), nullable=False),
    sa.Column('slab_smith_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('drafter_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('total_sqft_completed', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('file_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    create_table_if_not_exists('templatings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fab_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('schedule_start_date', sa.DateTime(), nullable=True),
    sa.Column('schedule_due_date', sa.DateTime(), nullable=True),
    sa.Column('total_sqft', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_templating_schedule', sa.Boolean(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    create_table_if_not_exists('work_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('curremt_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    drop_index_if_exists('ix_stone_types_name', 'stone_types')
    drop_table_if_exists('stone_types')
    drop_index_if_exists('ix_stone_colors_name', 'stone_colors')
    drop_table_if_exists('stone_colors')
    drop_index_if_exists('ix_edges_name', 'edges')
    drop_table_if_exists('edges')
    drop_index_if_exists('ix_stone_thickness_thickness', 'stone_thickness')
    drop_table_if_exists('stone_thickness')
    drop_index_if_exists('ix_accounts_account_number', 'accounts')
    drop_index_if_exists('ix_accounts_name', 'accounts')
    drop_table_if_exists('accounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    create_table_if_not_exists('accounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('account_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contact_person', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('accounts_created_by_fkey')),
    sa.ForeignKeyConstraint(['status_id'], ['status.value_id'], name=op.f('accounts_status_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('accounts_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('accounts_pkey')),
    sa.UniqueConstraint('account_number', name=op.f('accounts_account_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('name', name=op.f('accounts_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=False)
    op.create_index(op.f('ix_accounts_account_number'), 'accounts', ['account_number'], unique=False)
    create_table_if_not_exists('stone_thickness',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('thickness', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('thickness_mm', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('stone_thickness_created_by_fkey')),
    sa.ForeignKeyConstraint(['status_id'], ['status.value_id'], name=op.f('stone_thickness_status_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('stone_thickness_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stone_thickness_pkey')),
    sa.UniqueConstraint('thickness', name=op.f('stone_thickness_thickness_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_stone_thickness_thickness'), 'stone_thickness', ['thickness'], unique=False)
    create_table_if_not_exists('edges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('edge_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('edges_created_by_fkey')),
    sa.ForeignKeyConstraint(['status_id'], ['status.value_id'], name=op.f('edges_status_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('edges_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('edges_pkey')),
    sa.UniqueConstraint('name', name=op.f('edges_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_edges_name'), 'edges', ['name'], unique=False)
    create_table_if_not_exists('stone_colors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('color_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('stone_colors_created_by_fkey')),
    sa.ForeignKeyConstraint(['status_id'], ['status.value_id'], name=op.f('stone_colors_status_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('stone_colors_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stone_colors_pkey')),
    sa.UniqueConstraint('name', name=op.f('stone_colors_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_stone_colors_name'), 'stone_colors', ['name'], unique=False)
    create_table_if_not_exists('stone_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('stone_types_created_by_fkey')),
    sa.ForeignKeyConstraint(['status_id'], ['status.value_id'], name=op.f('stone_types_status_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('stone_types_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stone_types_pkey')),
    sa.UniqueConstraint('name', name=op.f('stone_types_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_stone_types_name'), 'stone_types', ['name'], unique=False)
    drop_table_if_exists('work_stations')
    drop_table_if_exists('templatings')
    drop_table_if_exists('slab_smiths')
    drop_table_if_exists('shop_planning_sections')
    drop_table_if_exists('shop_planning')
    drop_table_if_exists('sales_cts')
    drop_table_if_exists('pre_draft_reviews')
    drop_table_if_exists('planning_sections')
    drop_table_if_exists('operation_workflow')
    drop_table_if_exists('job_technician_workflows')
    drop_table_if_exists('final_programmings')
    drop_table_if_exists('draftings')
    drop_table_if_exists('cut_list')
    # ### end Alembic commands ###
