
"""Update user model

Revision ID: 2037f6ac1414
Revises: 
Create Date: 2025-01-20 19:35:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2037f6ac1414'
down_revision = '5d9efe4ffab9'
branch_labels = None
depends_on = None



def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_first_login', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_locked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_locked')
    op.drop_column('users', 'is_first_login')
    # ### end Alembic commands ###
