"""your migration message

Revision ID: 2cf5812425e7
Revises: 074512f0ca0f
Create Date: 2025-11-13 08:29:40.269973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cf5812425e7'
down_revision: Union[str, Sequence[str], None] = '074512f0ca0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None




def table_exists(table_name):
    """Check if a table exists in the database."""
    conn = op.get_bind()
    from sqlalchemy import inspect
    inspector = inspect(conn)
    return table_name in inspector.get_table_names()


def create_table_if_not_exists(table_name, *args, **kwargs):
    """Create a table only if it doesn't already exist."""
    if not table_exists(table_name):
        op.create_table(table_name, *args, **kwargs)
        print(f"Created table: {table_name}")
    else:
        print(f"Skipped table (already exists): {table_name}")

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
