"""autogen sync models 2

Revision ID: 3e6273d8b1c1
Revises: 940e119eecc6
Create Date: 2025-10-30 00:26:48.417131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e6273d8b1c1'
down_revision: Union[str, Sequence[str], None] = '940e119eecc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('permissions', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('permissions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.alter_column('role_permissions', 'action_menu_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('roles', 'update_at')
    op.drop_constraint(op.f('users_profile_image_id_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_status_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_role_id_fkey'), 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('users_role_id_fkey'), 'users', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(op.f('users_status_fkey'), 'users', 'status', ['status'], ['value_id'])
    op.create_foreign_key(op.f('users_profile_image_id_fkey'), 'users', 'files', ['profile_image_id'], ['id'])
    op.add_column('roles', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('roles', 'updated_at')
    op.alter_column('role_permissions', 'action_menu_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_column('permissions', 'updated_at')
    op.drop_column('permissions', 'description')
    op.drop_column('permissions', 'name')
    # ### end Alembic commands ###
