
# Revision identifiers, used by Alembic.
revision = '5d9efe4ffab9'
down_revision = None  # Set to previous revision id if exists
branch_labels = None
depends_on = None


from alembic import op
import sqlalchemy as sa


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_super_admin', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    op.drop_column('users', 'is_super_admin')
    # ### end Alembic commands ###
