"""Add new business tables

Revision ID: 834943c9a785
Revises: b45779835626
Create Date: 2025-11-07 22:22:43.413326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '834943c9a785'
down_revision: Union[str, Sequence[str], None] = 'b45779835626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create jobs table
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create fabs table
    op.create_table('fabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fab_type', sa.String(), nullable=False),
    sa.Column('stone_colour', sa.String(), nullable=False),
    sa.Column('stone_thickness', sa.String(), nullable=False),
    sa.Column('edges', sa.String(), nullable=False),
    sa.Column('input_area', sa.String(), nullable=False),
    sa.Column('totl_sqft', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('sales_person_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('template_needed', sa.Boolean(), nullable=False),
    sa.Column('drafting_needed', sa.Boolean(), nullable=False),
    sa.Column('slab_smith_needed_ag', sa.Boolean(), nullable=False),
    sa.Column('slab_smith_needed_cust', sa.Boolean(), nullable=False),
    sa.Column('sct_needed', sa.Boolean(), nullable=False),
    sa.Column('final_programming_needed', sa.Boolean(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('curremt_stage', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create planning_sections table
    op.create_table('planning_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create work_stations table
    op.create_table('work_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create shop_planning table
    op.create_table('shop_planning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create templatings table
    op.create_table('templatings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fab_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('schedule_start_date', sa.DateTime(), nullable=True),
    sa.Column('schedule_due_date', sa.DateTime(), nullable=True),
    sa.Column('total_sqft', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_templating_schedule', sa.Boolean(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create accounts table
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('descripition', sa.String(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('redraft_notes', sa.String(), nullable=True),
    sa.Column('schedule_start_date', sa.DateTime(), nullable=True),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('schedule_due_date', sa.DateTime(), nullable=True),
    sa.Column('total_sqft', sa.String(), nullable=True),
    sa.Column('technician_start_date', sa.DateTime(), nullable=True),
    sa.Column('technician_end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    op.drop_table('templatings')
    op.drop_table('shop_planning')
    op.drop_table('work_stations')
    op.drop_table('planning_sections')
    op.drop_table('fabs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
